'use client';

import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ChevronDown, Download, Eye, FileText, LoaderCircle, PencilLine, RefreshCw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ResumePaper } from '@/components/resume-paper';
import { analyzeJD } from '@/lib/jd-intelligence';
import { usePlatform } from '@/lib/platform-context';
import type { Candidate, Job, ResumeContent, ResumeVersion } from '@/lib/types';

type ResumeTab = 'Create' | 'In Review' | 'Approved' | 'History';

function Status({ value }: { value: string }) { return <span className={`candidate-status candidate-status--${value.toLowerCase().replaceAll(' ', '-')}`}>{value}</span>; }
function date(value: string) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }
function scoreColor(score: number) { return score >= 80 ? 'bg-emerald-500' : score >= 60 ? 'bg-amber-500' : 'bg-rose-500'; }

export function ResumeWorkspace({ initialJobId, onJobChange, notify }: { initialJobId: string | null; onJobChange: (id: string | null) => void; notify: (message: string, tone?: 'success' | 'error') => void }) {
  const { state, act, download, busy } = usePlatform();
  const [tab, setTab] = useState<ResumeTab>('Create');
  const [candidateId, setCandidateId] = useState('');
  const [template, setTemplate] = useState('Modern ATS');
  const [editing, setEditing] = useState(false);
  const [editContent, setEditContent] = useState<ResumeContent | null>(null);
  const job = state?.jobs.find(item => item.id === initialJobId);
  const candidate = state?.candidates.find(item => item.id === (job?.candidateId || candidateId));
  const jobs = state?.jobs.filter(item => !candidateId || item.candidateId === candidateId) ?? [];
  const versions = useMemo(() => state?.resumes.filter(item => item.jobId === initialJobId).sort((a, b) => b.version - a.version) ?? [], [state?.resumes, initialJobId]);
  const resume = versions[0];
  const analysis = job && candidate ? analyzeJD({ title: job.title, jdText: job.jdText, company: job.company, family: job.family }, candidate) : null;

  useEffect(() => { if (!candidateId && state?.candidates[0]) setCandidateId(state.candidates[0].id); }, [candidateId, state?.candidates]);
  useEffect(() => { if (job) { setCandidateId(job.candidateId); setTemplate(resume?.template ?? state?.settings.templates[0] ?? 'Modern ATS'); } }, [job?.id, resume?.id, state?.settings.templates]);
  if (!state) return null;

  const generate = async () => {
    if (!job) return;
    try { const result = await act('resume.generate', { jobId: job.id, template }); notify(result.message ?? 'Resume generated.'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not generate resume.', 'error'); }
  };
  const approve = async () => {
    if (!resume) return;
    try { const result = await act('resume.approve', { id: resume.id }); notify(result.message ?? 'Resume approved.'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not approve resume.', 'error'); }
  };
  const saveEdit = async () => {
    if (!resume || !editContent) return;
    try { const result = await act('resume.edit', { id: resume.id, content: editContent }); setEditing(false); notify(result.message ?? 'Resume version saved.'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not save edits.', 'error'); }
  };
  const downloadResume = (item: ResumeVersion, format: 'pdf' | 'docx') => void download({ resumeId: item.id, format }).catch(error => notify(error instanceof Error ? error.message : 'Download failed.', 'error'));
  const openResume = (item: ResumeVersion) => { onJobChange(item.jobId); setTab('Create'); };
  const tabRows = state.resumes.filter(item => tab === 'In Review' ? item.status === 'Ready for review' : tab === 'Approved' ? item.status === 'Approved' : true).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  return (
    <section>
      <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.1em] portal-accent-text">Resume workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.025em]">Create, review and approve resumes</h1><p className="mt-1 text-sm text-slate-500">Candidate context, JD intelligence and the resume stay together.</p></div>{resume && <Status value={resume.status} />}</div>
      <nav className="mb-4 flex gap-1 overflow-x-auto border-b bg-white px-2" aria-label="Resume workspace views">{(['Create', 'In Review', 'Approved', 'History'] as ResumeTab[]).map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-3 text-sm font-medium ${tab === item ? 'portal-accent-text border-current' : 'border-transparent text-slate-500'}`}>{item}{item === 'In Review' && state.resumes.some(resumeItem => resumeItem.status === 'Ready for review') ? ` (${state.resumes.filter(resumeItem => resumeItem.status === 'Ready for review').length})` : ''}</button>)}</nav>

      {tab !== 'Create' ? <ResumeList rows={tabRows} state={state} open={openResume} download={downloadResume} /> : !job ? (
        <div className="enterprise-surface p-4 sm:p-6"><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-semibold">Candidate</span><select value={candidateId} onChange={event => { setCandidateId(event.target.value); onJobChange(null); }} className="h-11 w-full border bg-white px-3 text-sm"><option value="">Select candidate</option>{state.candidates.filter(item => item.status === 'Active').map(item => <option key={item.id} value={item.id}>{item.name} · {item.family}</option>)}</select></label><label className="space-y-2"><span className="text-sm font-semibold">Approved job</span><select value="" onChange={event => onJobChange(event.target.value || null)} className="h-11 w-full border bg-white px-3 text-sm"><option value="">Select job</option>{jobs.map(item => <option key={item.id} value={item.id}>{item.company} · {item.title} · {item.matchScore}%</option>)}</select></label></div><p className="mt-4 text-sm text-slate-500">Select a candidate and approved job to open the full resume workspace.</p></div>
      ) : (
        <>
          <div className="enterprise-toolbar mb-4 flex flex-wrap items-center gap-2 border bg-white p-3"><div className="mr-auto min-w-[220px]"><p className="text-sm font-semibold">{candidate?.name} · {job.company}</p><p className="text-xs text-slate-500">{job.title} · {job.location}</p></div><Button variant="outline" onClick={() => onJobChange(null)}>Change selection</Button><Button onClick={() => void generate()} disabled={busy}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : resume ? <RefreshCw className="size-4" /> : <Sparkles className="size-4" />}{resume ? 'Regenerate' : 'Generate'}</Button>{resume && <><Button variant="outline" onClick={() => { setEditContent(structuredClone(resume.content)); setEditing(true); }}><PencilLine className="size-4" /> Edit</Button><Button variant="outline" onClick={() => downloadResume(resume, 'pdf')}><Download className="size-4" /> PDF</Button>{resume.status !== 'Approved' && <Button onClick={() => void approve()} className="bg-emerald-700 hover:bg-emerald-800"><CheckCircle2 className="size-4" /> Approve</Button>}</>}</div>
          <div className="resume-workspace-grid grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_300px]">
            <aside className="resume-context enterprise-surface h-fit p-4"><p className="panel-kicker">Context</p><h2 className="section-heading mt-1">Candidate + job</h2><dl className="mt-4 space-y-3"><Fact label="Candidate" value={candidate?.name} /><Fact label="Role" value={job.title} /><Fact label="Company" value={job.company} /><Fact label="Location" value={job.location} /><Fact label="Job family" value={job.family} /><Fact label="Match" value={`${job.matchScore}%`} /></dl><label className="mt-5 block space-y-2"><span className="text-xs font-semibold text-slate-500">Template</span><select value={template} onChange={event => setTemplate(event.target.value)} className="h-10 w-full border bg-white px-2 text-sm">{state.settings.templates.map(item => <option key={item}>{item}</option>)}</select></label><details className="mt-4 border-t pt-3 text-sm"><summary className="flex cursor-pointer list-none items-center justify-between font-medium">JD summary <ChevronDown className="size-4" /></summary><p className="mt-3 line-clamp-[12] whitespace-pre-wrap text-xs leading-5 text-slate-500">{job.jdText}</p></details></aside>
            <section className="resume-preview enterprise-surface min-h-[680px] overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><div><p className="font-semibold">Resume preview</p><p className="text-xs text-slate-500">{resume ? `Version ${resume.version} · ${resume.engine}` : 'Generate the first job-specific version'}</p></div>{resume && <Status value={resume.status} />}</div><div className="max-h-[820px] overflow-y-auto bg-slate-200 p-3 sm:p-6">{resume ? <ResumePaper content={resume.content} template={resume.template} /> : <div className="flex min-h-[560px] items-center justify-center bg-white p-8 text-center"><div><FileText className="mx-auto size-8 text-slate-300" /><p className="mt-3 font-semibold">Ready to generate</p><p className="mt-1 max-w-sm text-sm text-slate-500">The candidate evidence and JD intelligence are loaded. Generate when you are ready.</p><Button className="mt-4" onClick={() => void generate()}><Sparkles className="size-4" /> Generate resume</Button></div></div>}</div></section>
            <aside className="resume-intelligence enterprise-surface h-fit p-4"><p className="panel-kicker">Resume intelligence</p><h2 className="section-heading mt-1">JD alignment</h2>{analysis ? <><div className="mt-4 space-y-4"><Coverage label="Mandatory" score={analysis.coverage.mandatory.score} target={95} /><Coverage label="Required" score={analysis.coverage.required.score} target={80} /><Coverage label="Preferred" score={analysis.coverage.preferred.score} target={65} /><Coverage label="Overall JD" score={analysis.coverage.overallJD.score} /></div><IntelligenceGroup title="Primary skills" values={analysis.explicitSkills.slice(0, 8)} /><IntelligenceGroup title="Responsibilities" values={analysis.dayToDayResponsibilities.slice(0, 5)} /><IntelligenceGroup title="Adjacent tools" values={analysis.inferredSkills.slice(0, 6).map(item => `${item.skill} · ${Math.round(item.confidence * 100)}%`)} /><IntelligenceGroup title="Gaps to review" values={[...analysis.resumePlan.keywordGaps, ...analysis.resumePlan.qualificationConfirmations].slice(0, 8)} /><details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Technical details</summary><div className="mt-3 text-xs leading-5 text-slate-500"><p>{analysis.subFamily} · {analysis.seniority} · {analysis.domain}</p><p className="mt-2">{analysis.resumePlan.guardrails[0]}</p></div></details></> : <p className="mt-4 text-sm text-slate-500">JD intelligence is unavailable for this job.</p>}</aside>
          </div>
        </>
      )}
      <ResumeEditDialog open={editing} setOpen={setEditing} content={editContent} setContent={setEditContent} save={saveEdit} />
    </section>
  );
}

function Fact({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-0.5 text-sm font-semibold text-slate-800">{value || 'Not set'}</dd></div>; }
function Coverage({ label, score, target }: { label: string; score: number; target?: number }) { return <div><div className="mb-1 flex justify-between text-xs"><span className="text-slate-600">{label}</span><strong>{score}%{target ? ` / ${target}% target` : ''}</strong></div><div className="h-1.5 bg-slate-100"><div className={`h-full ${scoreColor(score)}`} style={{ width: `${Math.min(100, score)}%` }} /></div></div>; }
function IntelligenceGroup({ title, values }: { title: string; values: string[] }) { return <div className="mt-5 border-t pt-4"><h3 className="text-xs font-semibold uppercase tracking-[.06em] text-slate-500">{title}</h3><div className="mt-2 flex flex-wrap gap-1.5">{values.length ? values.map(value => <span key={value} className="bg-slate-100 px-2 py-1 text-xs text-slate-700">{value}</span>) : <span className="text-xs text-slate-400">None detected</span>}</div></div>; }

function ResumeList({ rows, state, open, download }: { rows: ResumeVersion[]; state: NonNullable<ReturnType<typeof usePlatform>['state']>; open: (resume: ResumeVersion) => void; download: (resume: ResumeVersion, format: 'pdf' | 'docx') => void }) {
  return <div className="enterprise-surface overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="border-b bg-slate-50 text-xs uppercase tracking-[.06em] text-slate-500"><th className="px-4 py-3">Candidate</th><th className="px-4 py-3">Job / company</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">JD match</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Generated</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{rows.map(item => { const job = state.jobs.find(jobItem => jobItem.id === item.jobId); const candidate = state.candidates.find(candidateItem => candidateItem.id === item.candidateId); const latest = !state.resumes.some(other => other.jobId === item.jobId && other.version > item.version); return <tr key={item.id} className="border-b last:border-0"><td className="px-4 py-3 font-semibold">{candidate?.name}</td><td className="px-4 py-3"><p className="font-semibold">{job?.title}</p><p className="text-xs text-slate-500">{job?.company}</p></td><td className="px-4 py-3">v{item.version} {latest && <span className="ml-1 text-xs portal-accent-text">Current</span>}</td><td className="px-4 py-3 font-semibold">{item.scores.jdMatch}%</td><td className="px-4 py-3"><Status value={item.status} /></td><td className="px-4 py-3 text-xs text-slate-500">{date(item.createdAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => open(item)}><Eye className="size-4" /> View</Button><Button size="sm" variant="outline" onClick={() => download(item, 'pdf')}><Download className="size-4" /></Button></div></td></tr>; })}</tbody></table></div><div className="divide-y md:hidden">{rows.map(item => { const job = state.jobs.find(jobItem => jobItem.id === item.jobId); const candidate = state.candidates.find(candidateItem => candidateItem.id === item.candidateId); return <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{job?.title}</p><p className="text-xs text-slate-500">{candidate?.name} · {job?.company}</p></div><Status value={item.status} /></div><div className="mt-3 flex items-center justify-between text-xs"><span>v{item.version} · {item.scores.jdMatch}% · {date(item.createdAt)}</span><Button size="sm" variant="outline" onClick={() => open(item)}>View</Button></div></article>; })}</div>{!rows.length && <p className="p-8 text-center text-sm text-slate-500">No resumes in this view.</p>}</div>;
}

function ResumeEditDialog({ open, setOpen, content, setContent, save }: { open: boolean; setOpen: (open: boolean) => void; content: ResumeContent | null; setContent: (content: ResumeContent | null) => void; save: () => Promise<void> }) {
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="corporate-dialog corporate-dialog--medium overflow-y-auto"><DialogHeader><DialogTitle>Edit resume</DialogTitle><DialogDescription>Saving creates a new immutable version.</DialogDescription></DialogHeader>{content && <div className="grid gap-4"><label className="space-y-1"><span className="text-sm font-semibold">Headline</span><input value={content.headline} onChange={event => setContent({ ...content, headline: event.target.value })} className="h-10 w-full border px-3" /></label><label className="space-y-1"><span className="text-sm font-semibold">Professional summary</span><textarea value={content.summary} onChange={event => setContent({ ...content, summary: event.target.value })} className="min-h-28 w-full border p-3" /></label><label className="space-y-1"><span className="text-sm font-semibold">Skills</span><textarea value={content.skills.join(', ')} onChange={event => setContent({ ...content, skills: event.target.value.split(',').map(item => item.trim()).filter(Boolean) })} className="min-h-20 w-full border p-3" /></label><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-semibold">Experience</p><Button size="sm" variant="outline" onClick={() => setContent({ ...content, experience: [...content.experience, { title: '', company: '', location: '', dates: '', bullets: [] }] })}>Add role</Button></div>{content.experience.map((role, index) => <div key={index} className="mb-3 border p-3"><div className="grid gap-2 sm:grid-cols-2">{(['title', 'company', 'location', 'dates'] as const).map(key => <input key={key} aria-label={key} placeholder={key} value={role[key]} onChange={event => { const experience = [...content.experience]; experience[index] = { ...role, [key]: event.target.value }; setContent({ ...content, experience }); }} className="h-9 border px-2 text-sm" />)}</div><textarea aria-label="Bullets" value={role.bullets.join('\n')} onChange={event => { const experience = [...content.experience]; experience[index] = { ...role, bullets: event.target.value.split('\n').map(item => item.trim()).filter(Boolean) }; setContent({ ...content, experience }); }} className="mt-2 min-h-24 w-full border p-2 text-sm" /></div>)}</div></div>}<DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!content?.headline || !content?.summary} onClick={() => void save()}>Save new version</Button></DialogFooter></DialogContent></Dialog>;
}
