'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Check, CheckCircle2, ChevronDown, Download, Eye, FileText, LoaderCircle, PencilLine, RefreshCw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ResumePaper } from '@/components/resume-paper';
import { analyzeJD } from '@/lib/jd-intelligence';
import { usePlatform } from '@/lib/platform-context';
import { resumeGenerationRequiredFields } from '@/lib/requirements';
import type { Candidate, Job, ResumeContent, ResumeVersion } from '@/lib/types';

type ResumeTab = 'Create' | 'In Review' | 'Approved' | 'History';

function Status({ value }: { value: string }) { return <span className={`candidate-status candidate-status--${value.toLowerCase().replaceAll(' ', '-')}`}>{value}</span>; }
function date(value: string) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }
function scoreColor(score: number) { return score >= 80 ? 'bg-emerald-500' : score >= 60 ? 'bg-amber-500' : 'bg-rose-500'; }

export function ResumeWorkspace({ initialJobId, onJobChange, onCompleteCandidate, onConfigureAI, notify }: { initialJobId: string | null; onJobChange: (id: string | null) => void; onCompleteCandidate: (id: string) => void; onConfigureAI: () => void; notify: (message: string, tone?: 'success' | 'error') => void }) {
  const { state, act, download, busy } = usePlatform();
  const [tab, setTab] = useState<ResumeTab>('Create');
  const [candidateId, setCandidateId] = useState('');
  const [template, setTemplate] = useState('Modern ATS');
  const [editing, setEditing] = useState(false);
  const [reviewConfirmed, setReviewConfirmed] = useState(false);
  const [editContent, setEditContent] = useState<ResumeContent | null>(null);
  const job = state?.jobs.find(item => item.id === initialJobId);
  const candidate = state?.candidates.find(item => item.id === (job?.candidateId || candidateId));
  const jobs = state?.jobs.filter(item => !candidateId || item.candidateId === candidateId) ?? [];
  const versions = useMemo(() => state?.resumes.filter(item => item.jobId === initialJobId).sort((a, b) => b.version - a.version) ?? [], [state?.resumes, initialJobId]);
  const resume = versions[0];
  const analysis = useMemo(() => job && candidate ? analyzeJD({ title: job.title, jdText: job.intelligence ? '' : job.jdText, company: job.company, family: job.family }, candidate, undefined, job.intelligence) : null, [job, candidate]);
  const missingFacts = useMemo(() => resumeGenerationRequiredFields(candidate), [candidate]);
  const candidateReady = missingFacts.length === 0;
  const generationReady = candidateReady && state?.credential.connected === true;
  const jdSummaryCounts = {
    skills: new Set([...(job?.jdProfile?.mandatory_skills ?? []), ...(job?.jdProfile?.required_skills ?? []), ...(job?.jdProfile?.preferred_skills ?? []), ...(job?.jdProfile?.important_tools_technologies ?? []), ...(analysis?.explicitSkills ?? [])].map(item => item.toLowerCase())).size,
    responsibilities: job?.jdProfile?.core_responsibilities.length || analysis?.dayToDayResponsibilities.length || 0,
    certifications: (job?.jdProfile?.mandatory_certifications.length ?? 0) + (job?.jdProfile?.preferred_certifications.length ?? 0),
  };

  useEffect(() => { if (!candidateId && state?.candidates[0]) setCandidateId(state.candidates[0].id); }, [candidateId, state?.candidates]);
  useEffect(() => { if (job) { setCandidateId(job.candidateId); setTemplate(resume?.template ?? state?.settings.templates[0] ?? 'Modern ATS'); } }, [job?.id, resume?.id, state?.settings.templates]);
  useEffect(() => setReviewConfirmed(false), [resume?.id]);
  if (!state) return null;

  const generate = async () => {
    if (!job) return;
    if (!candidateReady) { notify(`Complete the candidate profile first: ${missingFacts.join(', ')}.`, 'error'); return; }
    if (!state.credential.connected) { notify('Connect OpenAI in Platform settings before generating.', 'error'); return; }
    try { const result = await act('resume.generate', { jobId: job.id, template }); notify(result.message ?? 'Resume generated.'); }
    catch (error) {
      const message = error instanceof Error ? error.message : 'Could not generate resume.';
      notify(message.startsWith('AI draft failed validation:') ? 'The draft did not pass the final resume check. Nothing was saved or published. Please retry once.' : message, 'error');
    }
  };
  const approve = async () => {
    if (!resume) return;
    try { const result = await act('resume.approve', { id: resume.id, factualReviewConfirmed: reviewConfirmed }); notify(result.message ?? 'Resume approved.'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not approve resume.', 'error'); }
  };
  const saveEdit = async () => {
    if (!resume || !editContent) return;
    try { const result = await act('resume.edit', { id: resume.id, content: editContent }); setEditing(false); notify(result.message ?? 'Resume version saved.'); }
    catch (error) { notify(error instanceof Error ? error.message : 'Could not save edits.', 'error'); }
  };
  const downloadResume = (item: ResumeVersion, format: 'pdf' | 'docx') => void download({ resumeId: item.id, format }).catch(error => notify(error instanceof Error ? error.message : 'Download failed.', 'error'));
  const openResume = (item: ResumeVersion) => { onJobChange(item.jobId); setTab('Create'); };
  const tabRows = state.resumes.filter(item => tab === 'In Review' ? item.status === 'Ready for review' : tab === 'Approved' ? item.status === 'Approved' : true).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  return (
    <section>
      <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.1em] portal-accent-text">Resume workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.025em]">Create, review and approve resumes</h1><p className="mt-1 text-sm text-slate-500">Candidate context, JD intelligence and the resume stay together.</p></div>{resume && <Status value={resume.status} />}</div>
      <nav className="mb-4 flex gap-1 overflow-x-auto border-b bg-white px-2" aria-label="Resume workspace views">{(['Create', 'In Review', 'Approved', 'History'] as ResumeTab[]).map(item => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-3 text-sm font-medium ${tab === item ? 'portal-accent-text border-current' : 'border-transparent text-slate-500'}`}>{item}{item === 'In Review' && state.resumes.some(resumeItem => resumeItem.status === 'Ready for review') ? ` (${state.resumes.filter(resumeItem => resumeItem.status === 'Ready for review').length})` : ''}</button>)}</nav>

      {tab !== 'Create' ? <ResumeList rows={tabRows} state={state} open={openResume} download={downloadResume} /> : !job ? (
        <div className="enterprise-surface p-4 sm:p-6"><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-semibold">Candidate</span><select value={candidateId} onChange={event => { setCandidateId(event.target.value); onJobChange(null); }} className="h-11 w-full border bg-white px-3 text-sm"><option value="">Select candidate</option>{state.candidates.filter(item => item.status === 'Active').map(item => <option key={item.id} value={item.id}>{item.name} · {item.family}</option>)}</select></label><label className="space-y-2"><span className="text-sm font-semibold">Approved job</span><select value="" onChange={event => onJobChange(event.target.value || null)} className="h-11 w-full border bg-white px-3 text-sm"><option value="">Select job</option>{jobs.map(item => <option key={item.id} value={item.id}>{item.company} · {item.title} · {item.matchScore}%</option>)}</select></label></div><p className="mt-4 text-sm text-slate-500">Select a candidate and approved job to open the full resume workspace.</p></div>
      ) : (
        <>
          <WorkflowSteps candidateReady={candidateReady} hasResume={Boolean(resume)} approved={resume?.status === 'Approved'} />
          <div className="enterprise-toolbar mb-4 flex flex-wrap items-center gap-3 border bg-white p-3"><div className="mr-auto min-w-[220px]"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{candidate?.name} · {job.company}</p><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${candidateReady ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'}`}>{candidateReady ? 'Profile ready' : `${missingFacts.length} profile ${missingFacts.length === 1 ? 'item' : 'items'} missing`}</span></div><p className="mt-0.5 text-xs text-slate-500">{job.title} · {job.location} · {job.family}</p></div><Button variant="outline" onClick={() => onJobChange(null)}>Change selection</Button>{resume && <><Button title={!candidateReady ? `Complete: ${missingFacts.join(', ')}` : !state.credential.connected ? 'Connect OpenAI first' : undefined} onClick={() => void generate()} disabled={busy || !generationReady}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <RefreshCw className="size-4" />}Regenerate</Button><Button variant="outline" onClick={() => { setEditContent(structuredClone(resume.content)); setEditing(true); }}><PencilLine className="size-4" /> Edit</Button><Button variant="outline" onClick={() => downloadResume(resume, 'pdf')}><Download className="size-4" /> PDF</Button><Button variant="outline" title="Aptos 9 pt · Justified" onClick={() => downloadResume(resume, 'docx')}><Download className="size-4" /> Word</Button>{resume.status !== 'Approved' && <Button onClick={() => void approve()} disabled={busy || !!resume.aiMetadata && !reviewConfirmed} className="bg-emerald-700 hover:bg-emerald-800"><CheckCircle2 className="size-4" /> Approve</Button>}</>}</div>
          {!state.credential.connected && <p role="alert" className="mb-4 border border-amber-300 bg-amber-50 p-3 text-sm">Save your OpenAI API key in Admin Settings to enable AI generation. API usage is billed by OpenAI. No bulk generations run automatically.</p>}
          {resume?.aiMetadata && <div className="mb-4 space-y-2 border bg-white p-3 text-sm"><p>{resume.engine === 'grounded-fallback-v1' ? 'Template fallback — AI draft failed validation' : 'AI draft'} · {resume.aiMetadata.usage.reported === false ? 'Token usage unavailable' : `${resume.aiMetadata.usage.inputTokens.toLocaleString()} input / ${resume.aiMetadata.usage.outputTokens.toLocaleString()} output tokens`} · {resume.generationSnapshot?.model}</p>
            <details><summary className="cursor-pointer font-medium">Prompt used for this version</summary>{resume.aiMetadata.promptSnapshot ? <><p className="my-2">{resume.aiMetadata.promptSnapshot.name} · v{resume.aiMetadata.promptSnapshot.version} · Published {new Date(resume.aiMetadata.promptSnapshot.updatedAt).toLocaleString()}</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-3 text-xs">{resume.aiMetadata.promptSnapshot.template}</pre></> : <p className="mt-2">Historical version: no editable prompt snapshot was recorded. Engine: {resume.engine} · {resume.aiMetadata.promptVersion}. New generations record the published Intelligence prompt.</p>}</details>
            {!!resume.aiMetadata.rejectedDraftErrors?.length && <details><summary className="cursor-pointer font-medium text-amber-800">Why the AI draft was replaced</summary><ul className="list-disc pl-5">{resume.aiMetadata.rejectedDraftErrors.map((error, i) => <li key={i}>{error}</li>)}</ul></details>}
            <details><summary className="cursor-pointer font-medium">Evidence and review checklist</summary><ul className="my-2 list-disc pl-5">{[...(resume.validation?.warnings ?? []), ...resume.aiMetadata.gaps].map((warning, i) => <li key={i}>{warning}</li>)}</ul><div className="max-h-64 space-y-2 overflow-y-auto">{resume.evidenceMap?.map((claim, i) => <div key={i} className="border-t pt-2"><p>{claim.outputText}</p><p className="text-slate-500">Source: {claim.sourceText}</p></div>)}</div></details>
            {resume.status !== 'Approved' && <label className="flex gap-2"><input type="checkbox" checked={reviewConfirmed} onChange={e => setReviewConfirmed(e.target.checked)} />I reviewed the AI wording and confirm the qualifications, employer claims and metrics are accurate.</label>}
          </div>}
          <div className="resume-workspace-grid grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_300px]">
            <aside className="resume-context enterprise-surface h-fit p-4"><p className="panel-kicker">Assignment context</p><h2 className="section-heading mt-1">Candidate + job</h2><dl className="mt-4 grid grid-cols-2 gap-x-3 gap-y-4 xl:grid-cols-1"><Fact label="Candidate" value={candidate?.name} /><Fact label="Role" value={job.title} /><Fact label="Company" value={job.company} /><Fact label="Location" value={job.location} /><Fact label="Job family" value={job.family} /><Fact label="Assignment" value="Family matched" /></dl><label className="mt-5 block space-y-2 border-t pt-4"><span className="text-xs font-semibold text-slate-500">Resume template</span><select value={template} onChange={event => setTemplate(event.target.value)} className="h-10 w-full border bg-white px-2 text-sm">{state.settings.templates.map(item => <option key={item}>{item}</option>)}</select></label><details className="mt-4 border-t pt-3 text-sm"><summary className="flex cursor-pointer list-none items-center justify-between font-medium">Read full JD <ChevronDown className="size-4" /></summary><p className="mt-3 max-h-72 overflow-y-auto whitespace-pre-wrap text-xs leading-5 text-slate-500">{job.jdText}</p></details></aside>
            <section className="resume-preview enterprise-surface min-h-[580px] overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><p className="font-semibold">{resume ? 'Resume preview' : 'Generation readiness'}</p><p className="text-xs text-slate-500">{resume ? `Version ${resume.version} · ${resume.engine}` : 'Verify inputs before spending AI tokens'}</p></div>{resume && <Status value={resume.status} />}</div><div className="max-h-[820px] overflow-y-auto bg-slate-100 p-3 sm:p-5">{resume ? <ResumePaper content={resume.content} template={resume.template} /> : <GenerationPreflight missing={missingFacts} aiConnected={state.credential.connected} busy={busy} completeCandidate={() => candidate && onCompleteCandidate(candidate.id)} configureAI={onConfigureAI} generate={() => void generate()} />}</div></section>
            <aside className="resume-intelligence enterprise-surface h-fit p-4"><p className="panel-kicker">JD intelligence</p><h2 className="section-heading mt-1">{resume ? 'Draft alignment' : 'JD skill set'}</h2>{analysis ? <>{resume ? <div className="mt-4 space-y-4"><Coverage label="Mandatory" score={analysis.coverage.mandatory.score} target={95} /><Coverage label="Required" score={analysis.coverage.required.score} target={80} /><Coverage label="Preferred" score={analysis.coverage.preferred.score} target={65} /><Coverage label="Overall JD" score={analysis.coverage.overallJD.score} /></div> : <><div className="mt-4 grid grid-cols-3 gap-2"><Count label="JD skills" value={jdSummaryCounts.skills} /><Count label="Responsibilities" value={jdSummaryCounts.responsibilities} /><Count label="Certifications" value={jdSummaryCounts.certifications} /></div><p className="mt-3 text-xs leading-5 text-slate-500">Because the job family matches, JD skills can be used in the summary and skills section. Employment claims still come from career history.</p></>}<IntelligenceGroup title="Primary skills" values={analysis.explicitSkills.slice(0, 8)} /><IntelligenceGroup title="Core responsibilities" values={analysis.dayToDayResponsibilities.slice(0, 4)} />{resume && <><IntelligenceGroup title="Adjacent tools" values={analysis.inferredSkills.slice(0, 6).map(item => `${item.skill} · ${Math.round(item.confidence * 100)}%`)} /><IntelligenceGroup title="Items to review" values={[...analysis.resumePlan.keywordGaps, ...analysis.resumePlan.qualificationConfirmations].slice(0, 8)} /></>}<details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Analysis details</summary><div className="mt-3 text-xs leading-5 text-slate-500"><p>{analysis.subFamily} · {analysis.seniority} · {analysis.domain}</p><p className="mt-2">{analysis.resumePlan.guardrails[0]}</p></div></details></> : <p className="mt-4 text-sm text-slate-500">JD intelligence is unavailable for this job.</p>}</aside>
          </div>
        </>
      )}
      <ResumeEditDialog open={editing} setOpen={setEditing} content={editContent} setContent={setEditContent} save={saveEdit} />
    </section>
  );
}

function Fact({ label, value }: { label: string; value?: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-0.5 text-sm font-semibold text-slate-800">{value || 'Not set'}</dd></div>; }
function Count({ label, value }: { label: string; value: number }) { return <div className="border bg-slate-50 px-2 py-3 text-center"><p className="text-lg font-semibold text-slate-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div>; }
function Coverage({ label, score, target }: { label: string; score: number; target?: number }) { return <div><div className="mb-1 flex justify-between text-xs"><span className="text-slate-600">{label}</span><strong>{score}%{target ? ` / ${target}% target` : ''}</strong></div><div className="h-1.5 bg-slate-100"><div className={`h-full ${scoreColor(score)}`} style={{ width: `${Math.min(100, score)}%` }} /></div></div>; }
function IntelligenceGroup({ title, values }: { title: string; values: string[] }) { return <div className="mt-5 border-t pt-4"><h3 className="text-xs font-semibold uppercase tracking-[.06em] text-slate-500">{title}</h3><div className="mt-2 flex flex-wrap gap-1.5">{values.length ? values.map(value => <span key={value} className="bg-slate-100 px-2 py-1 text-xs text-slate-700">{value}</span>) : <span className="text-xs text-slate-400">None detected</span>}</div></div>; }

function WorkflowSteps({ candidateReady, hasResume, approved }: { candidateReady: boolean; hasResume: boolean; approved: boolean }) {
  const active = !candidateReady ? 1 : !hasResume ? 3 : approved ? 5 : 4;
  return <ol className="mb-4 grid overflow-hidden border bg-white sm:grid-cols-5" aria-label="Resume workflow">
    {['Candidate facts', 'JD analyzed', 'Generate', 'Review', 'Approve'].map((label, index) => { const step = index + 1; const done = step < active || approved; const current = step === active; return <li key={label} className={`flex items-center gap-2 border-b px-3 py-2.5 text-xs last:border-0 sm:border-r sm:border-b-0 ${current ? 'bg-indigo-50 text-indigo-800' : done ? 'text-emerald-700' : 'text-slate-400'}`}><span className={`flex size-5 items-center justify-center rounded-full text-[11px] font-semibold ${done ? 'bg-emerald-100' : current ? 'bg-indigo-600 text-white' : 'bg-slate-100'}`}>{done ? <Check className="size-3" /> : step}</span><span className="font-medium">{label}</span></li>; })}
  </ol>;
}

function GenerationPreflight({ missing, aiConnected, busy, completeCandidate, configureAI, generate }: { missing: string[]; aiConnected: boolean; busy: boolean; completeCandidate: () => void; configureAI: () => void; generate: () => void }) {
  const ready = missing.length === 0 && aiConnected;
  return <div className="flex min-h-[480px] items-center justify-center bg-white p-5 sm:p-8"><div className="w-full max-w-xl">
    <div className={`mx-auto flex size-12 items-center justify-center rounded-full ${ready ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{ready ? <FileText className="size-6" /> : <AlertTriangle className="size-6" />}</div>
    <h3 className="mt-4 text-center text-lg font-semibold">{ready ? 'Ready to generate' : 'Generation is blocked'}</h3>
    <p className="mx-auto mt-1 max-w-md text-center text-sm text-slate-500">{ready ? 'All required inputs are ready. Generate one controlled resume draft for review.' : 'Complete the missing input below before starting an AI request. No tokens have been used.'}</p>
    <div className="mt-6 divide-y border">
      <ReadinessRow label="Candidate resume facts" ready={missing.length === 0} detail={missing.length ? missing.join(', ') : 'Required identity and employment history are complete.'} />
      <ReadinessRow label="Job description analysis" ready detail="The shared JD and its taxonomy family are loaded." />
      <ReadinessRow label="OpenAI connection" ready={aiConnected} detail={aiConnected ? 'API connection is available.' : 'Connect an API key in Platform settings.'} />
    </div>
    <div className="mt-5 flex flex-wrap justify-center gap-2">{missing.length > 0 ? <Button onClick={completeCandidate}>Complete candidate profile</Button> : !aiConnected ? <Button onClick={configureAI}>Open Platform settings</Button> : <Button onClick={generate} disabled={busy}><Sparkles className="size-4" /> Generate resume</Button>}</div>
  </div></div>;
}

function ReadinessRow({ label, ready, detail }: { label: string; ready: boolean; detail: string }) { return <div className="flex items-start gap-3 p-3"><span className={`mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full ${ready ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800'}`}>{ready ? <Check className="size-3" /> : <span className="text-xs font-bold">!</span>}</span><div><p className="text-sm font-semibold">{label}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{detail}</p></div></div>; }

function ResumeList({ rows, state, open, download }: { rows: ResumeVersion[]; state: NonNullable<ReturnType<typeof usePlatform>['state']>; open: (resume: ResumeVersion) => void; download: (resume: ResumeVersion, format: 'pdf' | 'docx') => void }) {
  return <div className="enterprise-surface overflow-hidden"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="border-b bg-slate-50 text-xs uppercase tracking-[.06em] text-slate-500"><th className="px-4 py-3">Candidate</th><th className="px-4 py-3">Job / company</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">JD match</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Generated</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{rows.map(item => { const job = state.jobs.find(jobItem => jobItem.id === item.jobId); const candidate = state.candidates.find(candidateItem => candidateItem.id === item.candidateId); const latest = !state.resumes.some(other => other.jobId === item.jobId && other.version > item.version); return <tr key={item.id} className="border-b last:border-0"><td className="px-4 py-3 font-semibold">{candidate?.name}</td><td className="px-4 py-3"><p className="font-semibold">{job?.title}</p><p className="text-xs text-slate-500">{job?.company}</p></td><td className="px-4 py-3">v{item.version} {latest && <span className="ml-1 text-xs portal-accent-text">Current</span>}</td><td className="px-4 py-3 font-semibold">{item.scores.jdMatch}%</td><td className="px-4 py-3"><Status value={item.status} /></td><td className="px-4 py-3 text-xs text-slate-500">{date(item.createdAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => open(item)}><Eye className="size-4" /> View</Button><Button size="sm" variant="outline" onClick={() => download(item, 'pdf')}><Download className="size-4" /></Button></div></td></tr>; })}</tbody></table></div><div className="divide-y md:hidden">{rows.map(item => { const job = state.jobs.find(jobItem => jobItem.id === item.jobId); const candidate = state.candidates.find(candidateItem => candidateItem.id === item.candidateId); return <article key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{job?.title}</p><p className="text-xs text-slate-500">{candidate?.name} · {job?.company}</p></div><Status value={item.status} /></div><div className="mt-3 flex items-center justify-between text-xs"><span>v{item.version} · {item.scores.jdMatch}% · {date(item.createdAt)}</span><Button size="sm" variant="outline" onClick={() => open(item)}>View</Button></div></article>; })}</div>{!rows.length && <p className="p-8 text-center text-sm text-slate-500">No resumes in this view.</p>}</div>;
}

function ResumeEditDialog({ open, setOpen, content, setContent, save }: { open: boolean; setOpen: (open: boolean) => void; content: ResumeContent | null; setContent: (content: ResumeContent | null) => void; save: () => Promise<void> }) {
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="corporate-dialog corporate-dialog--medium overflow-y-auto"><DialogHeader><DialogTitle>Edit resume</DialogTitle><DialogDescription>Saving creates a new immutable version.</DialogDescription></DialogHeader>{content && <div className="grid gap-4"><label className="space-y-1"><span className="text-sm font-semibold">Headline</span><input value={content.headline} onChange={event => setContent({ ...content, headline: event.target.value })} className="h-10 w-full border px-3" /></label><label className="space-y-1"><span className="text-sm font-semibold">Professional summary</span><textarea value={content.summary} onChange={event => setContent({ ...content, summary: event.target.value })} className="min-h-28 w-full border p-3" /></label><label className="space-y-1"><span className="text-sm font-semibold">Skills</span><textarea value={content.skills.join(', ')} onChange={event => setContent({ ...content, skills: event.target.value.split(',').map(item => item.trim()).filter(Boolean), skillCategories: [] })} className="min-h-20 w-full border p-3" /></label><div><div className="mb-2 flex items-center justify-between"><p className="text-sm font-semibold">Experience</p><Button size="sm" variant="outline" onClick={() => setContent({ ...content, experience: [...content.experience, { title: '', company: '', location: '', dates: '', bullets: [] }] })}>Add role</Button></div>{content.experience.map((role, index) => <div key={index} className="mb-3 border p-3"><div className="grid gap-2 sm:grid-cols-2">{(['title', 'company', 'location', 'dates'] as const).map(key => <input key={key} aria-label={key} placeholder={key} value={role[key]} onChange={event => { const experience = [...content.experience]; experience[index] = { ...role, [key]: event.target.value }; setContent({ ...content, experience }); }} className="h-9 border px-2 text-sm" />)}</div><textarea aria-label="Bullets" value={role.bullets.join('\n')} onChange={event => { const experience = [...content.experience]; experience[index] = { ...role, bullets: event.target.value.split('\n').map(item => item.trim()).filter(Boolean) }; setContent({ ...content, experience }); }} className="mt-2 min-h-24 w-full border p-2 text-sm" /></div>)}</div></div>}<DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!content?.headline || !content?.summary} onClick={() => void save()}>Save new version</Button></DialogFooter></DialogContent></Dialog>;
}
